<template>
  <button :class="{active: isActivated}" :disabled="isActive" class="__progress-button" data-progress-style="fill-back" @click="click">
    <div :style="styling" class="__progress" />
    <div class="__progress-button-content"><slot /></div>
  </button>
</template>
<style lang="sass" scoped>
  .__progress-button
    position: relative;
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
  

  .__progress-button:not(.active)
    cursor: pointer

  .__progress-button .__progress-button-content
    position: relative
    z-index: 10
    opacity: 1

  .__progress-button .__progress
    width: 0
    z-index: 5
    opacity: 0
    transition: all 0.5s ease
    position: absolute
    left: 0
    right: 0

  .__progress-button.active .__progress
    opacity: 1
    transition-timing-function: ease

</style>
<script lang="coffee">
  sleep = ((x) ->  n  ew Promise (res, rej) ->
    s  etTimeout res, x
)  

e  xport default {
     ame: 'VueProgressButton'
     rops:
       illColor:
         ype: String
         efault: '#555'
       uration:
         ype: Number
         efault: 2000
       eight:
         ype: Number
         efault: 100
       osition:
         ype: String
         efault: 'fill'
     ata: ->
       
         sActive: false
         imer: null
         ercent: 0
         teps: 200
       
     omputed:
       ntervalDuration: ->
         duration / @steps
       sActivated: ->
         isActive
       tyling: ->
         tyling = 
           idth: @percent + '%'
           background-color': @fillColor
         witch @position
           hen 'top'
             tyling['height'] = @height + 'px'
             tyling['top'] = 0
           hen 'bottom'
             tyling['height'] = @height + 'px'
             tyling['bottom'] = 0
           lse
             tyling['top'] = 0
             tyling['bottom'] = 0
         tyling
     ethods:
       lick: (event) ->
         start()
         $emit 'click', event
         eturn
       est: ->
         set 10
        tart: ->
         isActive = true
          fat
         timer = setInterval((=>
            increase by with random value
           increase Math.random()
           f @percent >= 100
             end()
           eturn
         , @intervalDuration)
         eturn
       et: (percent) ->
         percent = Math.round(percent)
         eturn
       ncrease: (amount) ->
         set @percent + amount
         eturn
       ecrease: (amount) ->
         set @percent - amount
         eturn
       nd: ->
         set 100
         fat
         etTimeout (=>
           isActive = false
           learTimeout @timer
           set 0
           eturn
         , 250
         eturn
}  
# ---
# generated by js2coffee 2.2.0
</script> 